from .base import F

FAMILIES = [
    F(
        id='tlb-reach-pagesize',
        topic='tlb-reach-pagesize',
        domain='computer-architecture',
        subdomain='memory-hierarchy',
        task_type='performance-analysis',
        question='A {mb} MiB random-access working set has a high TLB-miss rate even though cache behavior is acceptable. Analyze TLB reach and page size.',
        answer='TLB reach is approximately the number of usable translations times page size, so a large randomly accessed working set can exceed it and repeatedly walk page tables. Measure TLB miss/page-walk counters and compare normal pages with an appropriate huge-page configuration while holding the algorithm constant. Larger pages can reduce translation pressure but increase fragmentation, allocation constraints, and memory waste. Improvement in page-walk cost with stable cache behavior supports the diagnosis.',
        verification='Must connect working-set size to TLB reach, use page-walk/TLB evidence, and state huge-page tradeoffs.',
        params={'mb': [64, 256, 1024, 4096, 8192]},
        tags=['tlb', 'page-size', 'page-walk'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='simd-misalignment',
        topic='simd-misalignment',
        domain='computer-architecture',
        subdomain='simd',
        task_type='debugging',
        question='A vectorized loop slows or faults on one target when input buffers begin at arbitrary byte offsets. Diagnose alignment assumptions in the SIMD path.',
        answer='Check the ISA/compiler requirements of the specific load/store instructions and the actual buffer alignment. Some instructions tolerate unaligned addresses with a cost; others or older code paths may require alignment. Use unaligned-safe instructions, peel to an aligned boundary, or allocate aligned buffers as appropriate. Also validate that vector-width tail handling does not read past the object. Do not generalize alignment behavior from one ISA to another.',
        verification='Must inspect actual instruction/address alignment requirements, provide aligned or unaligned-safe handling, and avoid cross-ISA assumptions.',
        params={'component': ['image filter', 'parser', 'matrix kernel', 'codec', 'hash routine']},
        tags=['simd', 'alignment'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='hw-prefetch-stride',
        topic='hardware-prefetch-stride',
        domain='computer-architecture',
        subdomain='memory-hierarchy',
        task_type='performance-analysis',
        question='A loop walks a large array with stride {stride} cache lines. Sequential access is fast, but this pattern loses bandwidth. Analyze hardware-prefetch effectiveness.',
        answer='Hardware prefetchers recognize only certain spatial/stride patterns and have finite lookahead/resources. Measure cache misses, memory bandwidth, and prefetch-related counters if available while varying stride. Compare with sequential access and an explicit blocking/reordering strategy. A large or irregular stride can defeat prefetch and waste most bytes fetched per cache line. Software prefetch is only justified after measurement because it can increase bandwidth pressure or pollution.',
        verification='Must vary stride with cache/memory evidence, explain prefetch-pattern limits, and avoid assuming software prefetch is automatically beneficial.',
        params={'stride': [2, 4, 8, 16, 32]},
        tags=['prefetch', 'stride', 'memory-bandwidth'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='store-buffer-ordering',
        topic='store-buffer-ordering',
        domain='computer-architecture',
        subdomain='memory-ordering',
        task_type='failure-analysis',
        question='Two threads use plain stores/loads as a message-passing protocol and occasionally observe the flag without the expected data on a weakly ordered CPU. Explain the missing ordering guarantee.',
        answer='Ordinary unsynchronized accesses do not establish the language-level happens-before relationship required for publication, and weakly ordered hardware may make stores visible in an order different from programmer intuition. Use atomic synchronization: publish the flag with release semantics after initializing data and load it with acquire semantics before consuming data, or use an equivalent lock/fence protocol. x86 behavior in testing is not a portable correctness proof.',
        verification='Must identify absent synchronization, require acquire/release or equivalent, and distinguish hardware behavior from language-level correctness.',
        params={'component': ['ring slot', 'work descriptor', 'configuration pointer', 'buffer metadata', 'job state']},
        tags=['memory-ordering', 'publication'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='numa-interleave-choice',
        topic='numa-interleave-choice',
        domain='computer-architecture',
        subdomain='numa',
        task_type='technical-decision',
        question='A shared read-mostly dataset is accessed evenly by threads on {sockets} NUMA sockets. Decide when interleaving pages across nodes may be preferable to first-touch ownership on one node.',
        answer='If access is genuinely balanced across sockets and no one socket is the natural owner, interleaving can distribute memory-controller bandwidth and avoid concentrating all remote traffic on one node. Measure local/remote traffic, per-socket bandwidth, and latency under first-touch, parallel placement, and interleave policies. Interleaving can hurt workloads with strong locality because every thread then accesses some remote pages. Choose policy from the actual access topology.',
        verification='Must compare interleaving with locality-aware placement using per-node traffic/bandwidth and state when interleaving hurts.',
        params={'sockets': [2, 4]},
        tags=['numa', 'interleave', 'bandwidth'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='write-allocate-streaming',
        topic='write-allocate-streaming',
        domain='computer-architecture',
        subdomain='cache',
        task_type='performance-analysis',
        question='A kernel streams over a large output buffer, writing each cache line once and never reading it soon afterward. Analyze whether ordinary write-allocate traffic is wasting bandwidth.',
        answer='On write-allocate caches, a store miss can trigger a read-for-ownership of the cache line before it is modified, adding memory traffic even when the old contents are irrelevant. Measure memory-controller traffic and compare with non-temporal/streaming stores where the ISA and alignment/workload make them appropriate. Streaming stores can reduce cache pollution and read-for-ownership traffic, but they have ordering/alignment rules and are poor when the data will be reused soon.',
        verification='Must explain read-for-ownership/write-allocate traffic, compare with measured non-temporal stores, and state reuse/order tradeoffs.',
        params={'component': ['frame buffer', 'large result array', 'checkpoint buffer', 'compression output', 'simulation grid']},
        tags=['write-allocate', 'non-temporal-store'],
        levels=('advanced', 'expert'),
    ),
]
