from .base import F

FAMILIES = [
    F(
        id='optimizer-state-sharding',
        topic='optimizer-state-sharding',
        domain='compute-model-infrastructure',
        subdomain='distributed-training',
        task_type='technical-decision',
        question='Model parameters fit on each GPU, but optimizer states dominate memory and prevent the desired model size. Decide when optimizer-state sharding is appropriate.',
        answer='Shard optimizer states across data-parallel ranks so each device stores only a fraction instead of a full replica. Measure parameter, gradient, optimizer, and activation memory separately first. Sharding reduces memory at the cost of additional communication and more complex checkpoint/recovery behavior. If activations dominate instead, optimizer sharding attacks the wrong term. Validate peak memory and step time together rather than treating memory savings alone as success.',
        verification='Must identify optimizer state as the limiting term, explain sharding memory/communication tradeoff, and require memory plus step-time measurement.',
        params={'optimizer': ['AdamW', 'Adam', 'Adafactor-like optimizer', 'momentum SGD', '8-bit optimizer']},
        tags=['optimizer', 'sharding', 'gpu-memory'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='gradient-bucket-overlap',
        topic='gradient-bucket-overlap',
        domain='compute-model-infrastructure',
        subdomain='distributed-training',
        task_type='performance-analysis',
        question='Distributed training waits for one very large gradient all-reduce near the end of backward. Analyze gradient bucket sizing for communication overlap.',
        answer='Smaller buckets can launch all-reduces as groups of gradients become ready, overlapping communication with later backward compute. Buckets that are too small increase collective launch/protocol overhead, while buckets that are too large delay communication until late in the step. Use a timeline to measure ready times, collective duration, overlap, and step time across bucket sizes. Choose the knee for the actual topology/model.',
        verification='Must explain overlap versus launch-overhead tradeoff, use timeline evidence, and tune from measured step time/topology.',
        params={'model': ['transformer', 'CNN', 'mixture-of-experts model', 'encoder-decoder', 'multimodal model']},
        tags=['gradient-bucket', 'all-reduce', 'overlap'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='kernel-fusion-memorybound',
        topic='kernel-fusion-memorybound',
        domain='compute-model-infrastructure',
        subdomain='gpu-performance',
        task_type='design',
        question='A GPU graph executes several tiny elementwise kernels that each read and rewrite the same tensor. Design a fusion test.',
        answer='Fuse compatible operations so intermediate values stay in registers/on-chip state where possible and the tensor is read/written fewer times. Compare kernel count, global-memory bytes, occupancy/register pressure, and end-to-end latency. Fusion helps when launch and memory traffic dominate, but an overly large fused kernel can increase register pressure and reduce occupancy. Keep numerical semantics and synchronization dependencies unchanged.',
        verification='Must compare memory traffic/kernel count before and after fusion, include register/occupancy tradeoffs, and preserve numerical/dependency semantics.',
        params={'ops': ['bias+activation', 'normalization chain', 'optimizer update', 'mask+scale', 'elementwise residual path']},
        tags=['kernel-fusion', 'gpu', 'memory-bandwidth'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='straggler-step',
        topic='distributed-training-straggler',
        domain='compute-model-infrastructure',
        subdomain='distributed-training',
        task_type='troubleshooting',
        question='Synchronous training step time is determined by one rank that is intermittently much slower than the others. Troubleshoot the straggler.',
        answer="Collect per-rank timelines for compute, input loading, communication, host scheduling, and device clocks. Because synchronization waits for the slowest participant, one rank's storage stall, thermal/power limit, network path, data skew, or CPU input bottleneck can extend every step. Compare the slow rank's phase timings with peers and move/replace the suspected resource. Aggregate utilization can look healthy while synchronization amplifies one-rank variance.",
        verification='Must use per-rank phase timing, explain slowest-rank synchronization, and distinguish compute/input/network/host causes.',
        params={'ranks': [4, 8, 16, 32, 64]},
        tags=['distributed-training', 'straggler', 'profiling'],
        levels=('advanced', 'expert'),
    ),
]
