from .base import F

FAMILIES = [
    F(
        id='lease-clock-skew',
        topic='lease-clock-skew',
        domain='distributed-systems',
        subdomain='leases',
        task_type='failure-analysis',
        question='Two nodes use wall-clock timestamps for a distributed lease. After clock skew, both can briefly believe they own the lease. Explain the safety problem.',
        answer='A lease is safe only under explicit assumptions about clock uncertainty and communication. If nodes independently compare unsynchronized wall clocks, one can think a previous lease expired while the old owner still believes it is valid. Use a protocol with bounded clock uncertainty and safety margin, or avoid relying on client wall time for mutual exclusion. Pair ownership with monotonic fencing tokens so downstream resources reject stale owners. Time synchronization improves operations but is not, by itself, a proof of lease safety.',
        verification='Must connect skew to overlapping ownership belief, require explicit clock assumptions or an alternative protocol, and recommend fencing for downstream safety.',
        params={'resource': ['job', 'shard', 'lock', 'scheduler slot', 'storage partition']},
        tags=['lease', 'clock-skew', 'fencing'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='fencing-splitbrain',
        topic='fencing-splitbrain',
        domain='distributed-systems',
        subdomain='coordination',
        task_type='design',
        question='A failed primary becomes partitioned, a new primary is elected, and the old primary later resumes issuing writes to shared storage. Design a fencing mechanism.',
        answer='Assign each ownership grant a strictly increasing fencing token/epoch. Every write to the protected resource carries that token, and the storage/resource layer records the highest token seen and rejects operations from lower, stale epochs. Revoking a lease or electing a new primary is not enough if the old process can still reach the resource. Fencing moves stale-owner rejection to the place where conflicting effects occur.',
        verification='Must use monotonically increasing ownership tokens enforced by the protected resource and explain why election/lease state alone cannot stop a stale process.',
        params={'resource': ['volume', 'shard', 'queue partition', 'device', 'job']},
        tags=['fencing', 'split-brain', 'epoch'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='read-repair',
        topic='read-repair',
        domain='distributed-systems',
        subdomain='replication',
        task_type='technical-decision',
        question='A replicated store sometimes reads divergent versions from replicas. Decide when read repair is useful and why it cannot be the only repair mechanism.',
        answer='A read can compare replica versions, return the value chosen by the consistency/conflict rule, and asynchronously update stale replicas. This opportunistically repairs keys that are actually read. Cold keys may remain inconsistent indefinitely, so background anti-entropy/repair is still needed for complete convergence. Measure repair volume and read latency, and ensure version metadata makes stale versus newer data unambiguous.',
        verification='Must explain opportunistic repair on reads, identify the cold-key limitation, require version/conflict semantics, and retain background repair.',
        params={'resource': ['user profile', 'object metadata', 'feature flag', 'session', 'catalog item']},
        tags=['read-repair', 'replication'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='consistent-hash-vnodes',
        topic='consistent-hash-vnodes',
        domain='distributed-systems',
        subdomain='partitioning',
        task_type='performance-analysis',
        question='A consistent-hash ring has only one token per node and shows severe load imbalance with {nodes} nodes. Analyze the use of virtual nodes/tokens.',
        answer='With few random positions, key ranges can vary widely in size and create uneven load. Giving each physical node multiple well-distributed virtual positions usually smooths the distribution and makes incremental membership changes move smaller ranges. Measure keys/bytes/QPS per node before and after changing token count. Too many virtual nodes increase metadata/rebalancing complexity, so choose enough to meet balance goals rather than maximizing the count.',
        verification='Must connect sparse token placement to imbalance, explain how multiple virtual positions smooth ranges, and require measured balance versus metadata/rebalance cost.',
        params={'nodes': [4, 8, 16, 32, 64]},
        tags=['consistent-hashing', 'vnodes', 'load-balance'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='snapshot-install',
        topic='snapshot-install',
        domain='distributed-systems',
        subdomain='consensus',
        task_type='implementation',
        question='A consensus follower is so far behind that the leader has compacted the log entries it needs. Implement the recovery path using a snapshot.',
        answer="The leader transfers a complete snapshot representing state through a specific committed index/term. The follower writes it to temporary durable state, validates completeness/integrity, atomically installs it, discards log prefixes covered by the snapshot, then resumes replication from the snapshot boundary. Interrupted transfers must not replace the current state with a partial snapshot, and stale snapshots must not roll state backward. Membership/configuration state included in the snapshot must follow the protocol's rules.",
        verification='Must install only a complete validated snapshot, preserve atomic recovery after interruption, align log state to the snapshot index/term, and reject stale rollback.',
        params={'resource': ['state machine', 'metadata store', 'scheduler state', 'KV shard', 'configuration log']},
        tags=['snapshot', 'log-compaction', 'consensus'],
        levels=('advanced', 'expert'),
    ),
]
