from .base import F

FAMILIES = [
    F(
        id='dma-ring-overrun',
        topic='dma-ring-overrun',
        domain='embedded-systems',
        subdomain='dma',
        task_type='debugging',
        question='A peripheral DMA engine writes into a circular buffer faster than firmware occasionally consumes it. Data appears duplicated or missing after bursts. Diagnose ring overrun handling.',
        answer='Track producer position from DMA/hardware and consumer position from software with a defined modulo scheme. If the producer advances far enough to lap unread data, old samples are overwritten and position alone may become ambiguous without an overrun counter/epoch. Size the ring for worst-case service latency, process in bounded batches, and expose overrun status. Clearing the symptom by reading indices more often does not guarantee capacity under worst-case interrupt/critical-section delays.',
        verification='Must distinguish producer/consumer positions, detect lapping/overwrite explicitly, size from worst-case service latency, and expose overrun state.',
        params={'peripheral': ['UART', 'ADC', 'SPI', 'I2S', 'camera']},
        tags=['dma', 'ring-buffer', 'overrun'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='adc-aliasing',
        topic='adc-aliasing',
        domain='embedded-systems',
        subdomain='sampling',
        task_type='failure-analysis',
        question='An ADC samples a periodic signal at {fs} kHz and reports a much lower apparent frequency that changes when the sample rate is adjusted. Explain aliasing.',
        answer='Sampling cannot uniquely represent frequency content above the Nyquist limit without prior filtering. Components above half the sample rate can fold into lower apparent frequencies. Confirm by changing sample rate and observing the predicted alias movement, and inspect the analog spectrum. Use an anti-alias filter and a sample rate with sufficient margin for the signal bandwidth. Digital post-processing after aliased sampling cannot reconstruct information that was never captured unambiguously.',
        verification='Must explain Nyquist/alias folding, require sample-rate/spectrum evidence, and recommend adequate sampling plus analog anti-alias filtering.',
        params={'fs': [8, 16, 24, 48, 96]},
        tags=['adc', 'aliasing', 'sampling'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='i2c-clock-stretch',
        topic='i2c-clock-stretch',
        domain='embedded-systems',
        subdomain='i2c',
        task_type='troubleshooting',
        question='An I2C master works with most sensors but times out with one device that occasionally holds SCL low. Troubleshoot clock stretching support.',
        answer='Inspect SCL/SDA with a logic analyzer and compare the low period with the device datasheet and master-controller capabilities. A compliant slave may stretch the clock by holding SCL low while it is not ready; a master/driver with an overly short timeout or no stretch support can misclassify that as a bus fault. Configure supported timeout/stretch handling within system latency requirements. Also distinguish genuine stretching from a stuck bus caused by an interrupted transaction or electrical problem.',
        verification='Must identify SCL-low stretching, use waveform/datasheet evidence, verify master support/timeouts, and distinguish valid stretching from a stuck bus.',
        params={'sensor': ['temperature sensor', 'EEPROM', 'secure element', 'touch controller', 'ADC']},
        tags=['i2c', 'clock-stretching'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='debounce-state-machine',
        topic='debounce-state-machine',
        domain='embedded-systems',
        subdomain='gpio',
        task_type='implementation',
        question='A mechanical button generates many GPIO transitions for one press. Implement a debounce policy without blocking the whole firmware for {ms} ms.',
        answer='On an edge, record the time/state and start or reset a debounce timer/state machine. Accept a new stable logical state only after the input has remained consistently at that level for the debounce interval; then emit one event. Continue servicing other firmware work while waiting. For interrupt-driven GPIO, keep the ISR minimal and perform the timed validation outside it. The exact interval should come from switch characteristics and UX requirements rather than an arbitrary long busy-wait.',
        verification='Must avoid blocking delay loops, require a timed stable-state check, keep ISR work minimal, and produce one logical event per physical transition.',
        params={'ms': [5, 10, 20, 30, 50]},
        tags=['gpio', 'debounce', 'state-machine'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='flash-wear-log',
        topic='flash-wear-log',
        domain='embedded-systems',
        subdomain='flash',
        task_type='design',
        question='A device writes a small status record every {seconds} seconds to the same flash page. Design storage so the page does not wear out prematurely.',
        answer='Flash has finite erase/program endurance and often erases in blocks larger than one record. Use a log-structured or rotating set of slots/pages, append new records with sequence/version and integrity metadata, and erase/recycle only after consuming available slots. Batch or reduce writes when semantics permit. Recovery should choose the newest valid record after power loss. Estimate lifetime from write frequency, erase-block endurance, and wear distribution rather than assuming nominal flash capacity implies unlimited updates.',
        verification='Must distribute writes/erases, include power-loss-safe version/integrity recovery, and reason from write frequency/endurance.',
        params={'seconds': [1, 5, 10, 30, 60]},
        tags=['flash', 'wear-leveling', 'log'],
        levels=('advanced', 'expert'),
    ),
]
