from .base import F

FAMILIES = [
    F(
        id='systemd-startlimit',
        topic='systemd-startlimit',
        domain='linux-infrastructure',
        subdomain='systemd',
        task_type='configuration',
        question='A crashing service restarts hundreds of times per minute and floods logs. Configure systemd so restart remains automatic but runaway restart loops are bounded.',
        answer='Keep the desired `Restart=` policy, then configure unit start-rate limiting (`StartLimitIntervalSec=`/`StartLimitBurst=` or the version-appropriate equivalent) so repeated failures eventually stop automatic starts for the interval. Use `RestartSec=` to add delay between attempts. Pick values from recovery objectives, not arbitrary numbers, and alert when the limit is hit. Rate limiting prevents a tight restart loop; it does not fix the underlying crash.',
        verification='Must combine restart policy with bounded start-rate limiting and retry delay, explain the operational tradeoff, and require alerting/root-cause work.',
        params={'service': ['API', 'worker', 'agent', 'proxy', 'collector']},
        tags=['systemd', 'restart', 'start-limit'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='veth-mtu-tunnel',
        topic='veth-mtu-tunnel',
        domain='linux-infrastructure',
        subdomain='networking',
        task_type='troubleshooting',
        question='Containers communicate through a veth pair and an overlay tunnel. Small packets work but larger transfers fragment or stall. Give a Linux-side MTU troubleshooting plan.',
        answer='Inspect MTU on the container interface, veth pair, bridge, host uplink, and tunnel, and account for encapsulation overhead. Capture packets at multiple layers and verify ICMP packet-too-big/PMTU feedback is not blocked. The effective payload MTU must fit the smallest path after tunnel headers. Configure consistent MTUs or an intentional MSS/PMTU strategy rather than changing only the container interface.',
        verification='Must inspect MTU across veth/bridge/tunnel/uplink, include encapsulation overhead and PMTU feedback, and reject one-interface-only fixes.',
        params={'tunnel': ['VXLAN', 'WireGuard', 'GRE', 'Geneve', 'IP-in-IP']},
        tags=['veth', 'mtu', 'tunnel'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='io-scheduler-latency',
        topic='io-scheduler-latency',
        domain='linux-infrastructure',
        subdomain='storage',
        task_type='performance-analysis',
        question='A latency-sensitive database shares an SSD with background sequential writes. Analyze whether block I/O scheduling/queueing is hurting tail latency.',
        answer='Measure device latency distribution, queue depth, per-cgroup/process I/O, throughput, and scheduler policy under mixed load. Compare controlled runs with background traffic limited or isolated and, where appropriate, alternative scheduler/cgroup I/O policies. The right policy depends on the device and workload: modern NVMe behavior differs from rotational disks. The goal is to bound interference, not to pick a scheduler by name without evidence.',
        verification='Must use latency/queue/per-workload I/O evidence, test isolation or policy changes, and avoid universal scheduler claims.',
        params={'device': ['NVMe SSD', 'SATA SSD', 'virtual block device', 'RAID volume', 'cloud disk']},
        tags=['io-scheduler', 'storage', 'tail-latency'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='tmpfs-memory-pressure',
        topic='tmpfs-memory-pressure',
        domain='linux-infrastructure',
        subdomain='memory',
        task_type='failure-analysis',
        question='A service writes large temporary files to tmpfs. Disk usage looks fine, but the host develops memory pressure and swap activity. Explain why.',
        answer="tmpfs stores file contents in memory (and can use swap), so growth consumes the same broad memory resources that applications/page cache rely on rather than ordinary disk blocks. Measure tmpfs usage, resident/swap pressure, cgroup memory accounting, and the writer's lifecycle. Set explicit size/cgroup limits and clean up files. Treating tmpfs as 'free fast disk' can move a storage-capacity problem into memory pressure.",
        verification='Must connect tmpfs growth to memory/swap accounting, require usage/pressure evidence, and recommend bounded limits/cleanup.',
        params={'component': ['build worker', 'image processor', 'database temp area', 'test runner', 'cache']},
        tags=['tmpfs', 'memory-pressure'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='psi-capacity-signal',
        topic='psi-capacity-signal',
        domain='linux-infrastructure',
        subdomain='observability',
        task_type='technical-decision',
        question='A host shows only {cpu}% average CPU use, yet latency is poor. Decide how Linux Pressure Stall Information can add evidence beyond utilization.',
        answer='Utilization says how busy resources are but not how much time runnable work is stalled waiting for CPU, memory reclaim, or I/O. PSI reports time some/all tasks are delayed by resource pressure. Correlate CPU/memory/I/O PSI with service latency and cgroup-level metrics. High PSI with moderate average utilization can reveal concentrated contention or reclaim/IO stalls. PSI is a signal for investigation/capacity control, not a diagnosis by itself.',
        verification='Must distinguish utilization from stall time, correlate PSI dimensions with latency/cgroup evidence, and avoid treating PSI alone as root-cause proof.',
        params={'cpu': [40, 55, 65, 75, 80]},
        tags=['psi', 'observability', 'capacity'],
        levels=('advanced', 'expert'),
    ),
]
