from .base import F

FAMILIES = [
    F(
        id='syn-cookie-tradeoff',
        topic='syn-cookie-tradeoff',
        domain='networking',
        subdomain='tcp',
        task_type='technical-decision',
        question='A public TCP service experiences bursts that fill the SYN backlog. Decide when SYN cookies are an appropriate protection and what they do not solve.',
        answer='SYN cookies can allow the server to avoid retaining normal per-half-open-connection state when the SYN queue is under pressure, helping resist state exhaustion. They do not provide unlimited application capacity, do not stop established-connection resource exhaustion, and can constrain TCP option negotiation depending on implementation. Confirm backlog drops/SYN pressure first, keep normal backlog sizing and admission controls, and use cookies as one layer of protection rather than a substitute for DDoS filtering or capacity planning.',
        verification='Must explain half-open state protection, state limits of SYN cookies, require backlog-pressure evidence, and avoid presenting them as general DDoS/capacity protection.',
        params={'service': ['web server', 'API edge', 'SSH bastion', 'game gateway', 'proxy']},
        tags=['tcp', 'syn-cookie', 'backlog'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='ecn-congestion',
        topic='ecn-congestion',
        domain='networking',
        subdomain='congestion-control',
        task_type='performance-analysis',
        question='A controlled network supports ECN end-to-end. Analyze how ECN can signal congestion before packet loss and how to verify it is actually negotiated.',
        answer='ECN-capable endpoints can mark packets/echo congestion information instead of relying only on drops, allowing congestion control to reduce sending rate while avoiding some loss/retransmission cost. Verify negotiation in the handshake/protocol state and capture CE/ECE/CWR-style signals or stack counters as appropriate. Compare queue delay, retransmissions, and throughput with and without ECN under the same bottleneck. ECN does not create capacity; it changes congestion signalling behavior and depends on compatible endpoints/network devices.',
        verification='Must require end-to-end negotiation/counter evidence, compare congestion behavior, and state that ECN signals rather than removes congestion.',
        params={'path': ['datacenter fabric', 'WAN link', 'VPN path', 'cloud VPC', 'lab bottleneck']},
        tags=['ecn', 'congestion', 'tcp'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='dns-ttl-staleness',
        topic='dns-ttl-staleness',
        domain='networking',
        subdomain='dns',
        task_type='debugging',
        question='A client keeps connecting to an old service address minutes after DNS has changed. The authoritative record is correct. Diagnose TTL and local caching behavior.',
        answer='Inspect the record TTL, recursive resolver cache, OS/runtime/application DNS caches, and whether the client library pins resolved addresses longer than DNS semantics intend. Query each layer separately to locate stale state. A low authoritative TTL cannot force a runtime that caches forever to refresh correctly, while setting TTL near zero increases resolver load and may still be bounded by cache minimums. Fix the layer violating the desired refresh policy.',
        verification='Must inspect authoritative TTL plus resolver/OS/runtime caches, locate the stale layer, and avoid assuming authoritative DNS changes instantly reach clients.',
        params={'service': ['database', 'API', 'message broker', 'storage endpoint', 'load balancer']},
        tags=['dns', 'ttl', 'cache'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='tcp-autotune-window',
        topic='tcp-autotune-window',
        domain='networking',
        subdomain='tcp',
        task_type='troubleshooting',
        question='A high-bandwidth, high-RTT TCP transfer never reaches expected throughput. Loss is low, but the receive window remains small relative to the bandwidth-delay product. Troubleshoot socket-buffer/window sizing.',
        answer='Compute the approximate bandwidth-delay product and compare it with advertised receive window and send/receive buffer limits. Inspect window scaling negotiation and OS autotuning caps. If the usable window is below the amount of data needed in flight, throughput can be window-limited even without loss. Test larger appropriate socket/autotuning limits and verify window growth and throughput. Avoid blindly setting enormous buffers because they consume memory and can worsen queueing.',
        verification='Must compare window/buffer size with BDP, inspect scaling/autotuning, validate with a controlled buffer change, and include memory/queueing tradeoffs.',
        params={'rtt': [20, 50, 100, 150, 200]},
        tags=['tcp', 'window', 'bdp'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='h2-hol-tcp',
        topic='http2-tcp-head-of-line',
        domain='networking',
        subdomain='http2',
        task_type='failure-analysis',
        question='Multiple HTTP/2 streams share one TCP connection. One packet is lost and unrelated streams pause until retransmission arrives. Explain why stream multiplexing did not eliminate all head-of-line blocking.',
        answer='HTTP/2 multiplexes application streams, but all bytes still ride one ordered TCP byte stream. A missing TCP segment prevents later bytes from being delivered to HTTP/2 until retransmission fills the gap, so unrelated streams whose frames arrived later can stall. Confirm with packet loss/retransmission timing and stream traces. QUIC-style transports can avoid transport-level cross-stream HOL because streams are independently ordered, although they still experience congestion and loss.',
        verification="Must distinguish HTTP/2 application multiplexing from TCP's ordered byte stream and connect one lost segment to cross-stream delivery blocking.",
        params={'service': ['browser session', 'RPC gateway', 'CDN connection', 'mobile client', 'API client']},
        tags=['http2', 'tcp', 'head-of-line'],
        levels=('advanced', 'expert'),
    ),
]
