from .base import F

FAMILIES = [
    F(
        id='mlock-pagefault-budget',
        topic='mlock-pagefault-budget',
        domain='operating-systems',
        subdomain='virtual-memory',
        task_type='technical-decision',
        question='A latency-critical process wants to `mlock()` {mb} MiB to avoid page faults. Decide what must be considered before locking the entire working set.',
        answer='Locked pages avoid reclamation and can reduce fault/reclaim latency, but they permanently consume resident memory while locked and are constrained by resource limits/policy. Measure the truly latency-critical working set, prefault it if required, check `RLIMIT_MEMLOCK`/privileges, and leave sufficient memory for the rest of the system. Locking an oversized set can push memory pressure onto other processes or make deployment fail. Use targeted locking rather than assuming all process memory should be resident.',
        verification='Must discuss resident-memory cost, memlock limits/privileges, working-set measurement, prefaulting where relevant, and system-wide pressure.',
        params={'mb': [16, 64, 256, 1024, 4096]},
        tags=['mlock', 'page-fault', 'latency'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='cpu-affinity-migration',
        topic='cpu-affinity-migration',
        domain='operating-systems',
        subdomain='scheduler',
        task_type='performance-analysis',
        question='A cache-sensitive worker migrates frequently among CPUs and shows unstable latency. Analyze whether tighter affinity could help without assuming pinning is always better.',
        answer='Measure CPU migrations, cache/TLB miss behavior, run-queue pressure, NUMA locality, and latency. Pinning or a smaller affinity mask can improve locality when the worker repeatedly loses warm cache state, but it can hurt load balancing and create hotspots when chosen CPUs become busy. Compare unrestricted scheduling with topology-aware affinity under the same workload. The decision should balance locality against scheduler flexibility rather than treating migration count alone as a bug.',
        verification='Must measure migrations/locality and run-queue effects, test controlled affinity, and state the load-balancing tradeoff.',
        params={'component': ['packet worker', 'render worker', 'database thread', 'runtime worker', 'analytics task']},
        tags=['affinity', 'migration', 'cache-locality'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='hugepage-fragmentation',
        topic='hugepage-fragmentation',
        domain='operating-systems',
        subdomain='virtual-memory',
        task_type='troubleshooting',
        question='A workload requests large huge pages late in system uptime and allocation often fails despite plenty of total free memory. Troubleshoot fragmentation.',
        answer='Huge pages require sufficiently large contiguous physical regions (or reserved hugepage pools, depending on the mechanism). Total free memory can be ample but fragmented into smaller pieces. Inspect hugepage counters, compaction activity/failures, buddy allocator state, and allocation timing. Reserve huge pages early when predictable capacity is required, use appropriate page sizes/policies, or reduce fragmentation pressure. Treat repeated synchronous compaction as a latency cost rather than relying on free-byte totals.',
        verification='Must distinguish total free memory from contiguous allocatable regions, require fragmentation/compaction evidence, and discuss reservation/policy options.',
        params={'component': ['database', 'VM host', 'packet processor', 'scientific job', 'ML runtime']},
        tags=['hugepage', 'fragmentation', 'compaction'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='clock-source-timeout',
        topic='clock-source-timeout',
        domain='operating-systems',
        subdomain='timekeeping',
        task_type='code-repair',
        question='A timeout is computed from wall-clock time. When the administrator steps the clock backward, an operation waits far longer than intended. Repair the clock choice.',
        answer='Use a monotonic clock for measuring elapsed durations and deadlines that should not track civil-time adjustments. Capture a monotonic start/deadline and compare using that same clock domain. Keep wall time for timestamps presented to humans or calendar events. If suspend time must count toward the timeout, choose a monotonic/boottime clock with the required suspend semantics. Mixing clock domains in one deadline calculation is also a bug.',
        verification='Must replace wall-clock elapsed-time logic with an appropriate monotonic clock and state suspend/clock-domain semantics.',
        params={'component': ['RPC', 'lock acquisition', 'job', 'health check', 'retry']},
        tags=['monotonic-clock', 'timeout'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='writer-starvation-rwlock',
        topic='writer-starvation-rwlock',
        domain='operating-systems',
        subdomain='synchronization',
        task_type='failure-analysis',
        question='A read-heavy workload uses a reader/writer lock. Readers continuously arrive, and a waiting writer sometimes waits seconds although each reader is short. Explain writer starvation.',
        answer='If the lock implementation admits new readers while a writer is queued, a steady stream of readers can keep the writer from ever acquiring exclusive ownership. Measure reader arrival, writer wait time, and lock policy. Use a writer-preference/fair lock when bounded writer latency matters, or redesign with versioned/RCU-style reads if appropriate. Fairness policies can reduce peak reader throughput, so the fix should follow latency requirements rather than assuming one lock policy is universally best.',
        verification='Must identify admission of new readers ahead of a queued writer, require lock-policy evidence, and discuss fairness versus throughput.',
        params={'component': ['routing table', 'metadata map', 'cache index', 'configuration store', 'registry']},
        tags=['rwlock', 'starvation', 'fairness'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='overcommit-commit-charge',
        topic='overcommit-commit-charge',
        domain='operating-systems',
        subdomain='virtual-memory',
        task_type='debugging',
        question='A Linux process successfully reserves a very large anonymous mapping, but later allocations or page faults fail under strict memory-commit policy. Explain why virtual address reservation is not the same as committed backing.',
        answer="Virtual address space can be reserved without immediately consuming physical pages, and Linux overcommit policy determines when the kernel promises backing for anonymous memory. Under stricter commit accounting, the process can hit commit limits even though address-space reservation succeeded earlier. Inspect overcommit mode, commit limit/committed-as metrics, swap, cgroup limits, and the application's touched working set. Do not infer available usable memory from `mmap()` success alone.",
        verification='Must distinguish virtual reservation from commit/backing guarantees and require overcommit/commit/cgroup evidence.',
        params={'component': ['database', 'VM runtime', 'compiler', 'analytics process', 'ML loader']},
        tags=['overcommit', 'virtual-memory', 'commit-charge'],
        levels=('advanced', 'expert'),
    ),
]
