from .base import F

FAMILIES = [
    F(
        id='amdahl-speedup',
        topic='amdahl-speedup',
        domain='engineering-reasoning',
        subdomain='performance-modeling',
        task_type='performance-analysis',
        question='A workload spends {serial}% of runtime in code that cannot be parallelized. Estimate the theoretical maximum speedup with unlimited processors and explain what the bound means.',
        answer="Amdahl's Law gives maximum speedup `1 / f_serial`. With a serial fraction of {serial}%, `f_serial = {serial}/100`, so the unlimited-processor upper bound is `100/{serial}`×. This is a model bound, not a performance promise: synchronization, memory bandwidth, scheduling, and load imbalance can reduce real speedup further. The exercise is useful for deciding whether optimizing the serial portion may matter more than adding processors.",
        verification='Must compute the unlimited-processor bound as 100/{serial}, identify the serial fraction, and state that real systems can be slower due to additional overheads.',
        params={'serial': [5, 10, 20, 25, 40]},
        tags=['amdahl', 'speedup', 'parallelism'],
        levels=('intermediate', 'advanced'),
        verification_method='reference-answer',
    ),
    F(
        id='rto-rpo-backup',
        topic='rto-rpo-backup',
        domain='engineering-reasoning',
        subdomain='reliability',
        task_type='technical-decision',
        question='A service has an RPO of {rpo} minutes and an RTO of {rto} minutes. Explain how those two targets constrain backup/replication and recovery design.',
        answer='RPO bounds acceptable data loss, so the system needs replication/checkpoint/backup frequency and durability capable of losing no more than about {rpo} minutes of committed state under the defined disaster. RTO bounds how long service restoration may take, so restore automation, data volume, validation, failover capacity, and operator procedures must fit within {rto} minutes. A backup schedule can satisfy RPO yet still miss RTO if restoration is too slow. Test both with recovery exercises rather than inferring them from backup existence.',
        verification='Must distinguish data-loss objective (RPO {rpo} min) from restoration-time objective (RTO {rto} min) and require tested recovery.',
        params={'rpo': [1, 5, 15, 30, 60], 'rto': [5, 15]},
        tags=['rpo', 'rto', 'disaster-recovery'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='energy-performance',
        topic='energy-performance',
        domain='engineering-reasoning',
        subdomain='efficiency',
        task_type='technical-decision',
        question='Two compute configurations complete the same job: A uses {wa} W for {ta} minutes, while B uses {wb} W for {tb} minutes. Explain how to compare energy efficiency instead of power alone.',
        answer='Energy is power multiplied by time. Configuration A uses approximately `{wa} W × {ta}/60 h`; B uses `{wb} W × {tb}/60 h`. Compare watt-hours (or joules) for the completed job, then separately consider latency, thermal limits, electricity price, and hardware constraints. Lower instantaneous power does not guarantee lower total energy if the job runs much longer, and the lowest-energy choice may still be unacceptable if it misses a latency/SLA target.',
        verification='Must compare power×time energy for the same completed work and distinguish energy efficiency from instantaneous power and latency requirements.',
        params={'wa': [120, 180, 250, 320, 450], 'ta': [20, 30], 'wb': [100, 160], 'tb': [35]},
        tags=['energy', 'efficiency', 'power'],
        levels=('intermediate', 'advanced'),
        verification_method='reference-answer',
    ),
]
