from .base import F

FAMILIES = [
    F(
        id='circuit-breaker-half-open',
        topic='circuit-breaker-half-open',
        domain='software-engineering',
        subdomain='resilience',
        task_type='design',
        question='A {service} calls a flaky dependency. After the circuit opens, every instance retries at the same instant and overloads the recovering dependency. Design the half-open recovery behavior for about {clients} callers.',
        answer='Use a half-open state with a small, bounded number of probe requests rather than reopening full traffic immediately. Successful probes should close the circuit only after a defined threshold; failed probes reopen it. Add jitter to retry/probe timing so {clients} callers do not synchronize. Keep normal request deadlines and cancellation in force, and expose circuit state, probe success, and open duration as metrics. The circuit breaker protects a failing dependency from repeated load; it is not a replacement for per-request timeouts, capacity limits, or idempotency.',
        verification='Must bound half-open probes, prevent synchronized recovery traffic with jitter, define success/failure transitions, and keep ordinary timeout/cancellation semantics.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service'], 'clients': [100, 1000]},
        tags=['circuit-breaker', 'resilience'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='structured-concurrency-cancel',
        topic='structured-concurrency-cancellation',
        domain='software-engineering',
        subdomain='concurrency',
        task_type='implementation',
        question='A {service} starts {children} child tasks for one request. If one child fails or the client disconnects, the remaining tasks currently continue running in the background. Implement a structured-concurrency policy.',
        answer='Tie child task lifetime to the parent request scope. Create children under a task group/scope that propagates cancellation and joins them before the scope exits. If policy is fail-fast, the first substantive child failure cancels siblings; if partial success is allowed, encode that explicitly rather than leaking work. Ensure cleanup runs on cancellation and that shared resources are released exactly once. Detached background tasks should be used only when their lifetime is intentionally independent of the request.',
        verification='Must bind child lifetime to parent scope, propagate cancellation, join/clean up children, and distinguish intentional detached work from accidental task leakage.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service'], 'children': [8, 64]},
        tags=['structured-concurrency', 'cancellation'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='cache-admission-hotset',
        topic='cache-admission-hotset',
        domain='software-engineering',
        subdomain='caching',
        task_type='technical-decision',
        question='A {service} cache is polluted by one-hit objects from large scans, evicting a small hot set. The cache holds {size} GB. Decide how an admission policy can help.',
        answer='Separate admission from eviction. A frequency-aware admission policy can reject low-reuse scan objects even when space could be made by evicting hotter entries. Measure hit rate, eviction rate, reuse frequency, and backend load before and after the change. A policy such as TinyLFU-style admission is useful when the workload has a stable hot set plus scan pollution, but it adds metadata and is not universally better than plain LRU. Validate with production-like traces rather than only synthetic sequential scans.',
        verification='Must explain admission versus eviction, connect one-hit scan pollution to hot-item eviction, require trace-based measurement, and avoid claiming one policy is universally optimal.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service'], 'size': [4, 16]},
        tags=['cache', 'admission', 'hotset'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='listener-lifecycle-leak',
        topic='listener-lifecycle-leak',
        domain='software-engineering',
        subdomain='resource-management',
        task_type='debugging',
        question='A long-lived {service} dynamically registers event listeners for requests but memory grows over hours even after requests finish. The listener count also rises. Diagnose the likely ownership bug.',
        answer='Listeners retain callbacks and often the objects captured by those callbacks. If request-scoped listeners are never unregistered, the publisher becomes an unintended lifetime root. Correlate heap growth with listener counts and retained-object paths, then identify registration sites lacking symmetric removal on success, error, timeout, or cancellation. Repair the lifecycle with scoped subscriptions/disposables or explicit unregister in guaranteed cleanup. Raising the heap limit delays the symptom but leaves the retention graph intact.',
        verification='Must connect rising listener count to retained request objects, use heap/retainer evidence, and require symmetric listener cleanup on all exit paths.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service']},
        tags=['memory-leak', 'listeners', 'ownership'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='token-bucket-rate-limit',
        topic='token-bucket-rate-limit',
        domain='software-engineering',
        subdomain='admission-control',
        task_type='implementation',
        question='Implement a token-bucket limiter for a {service} allowing an average of {rate} requests/s with a short burst of {burst} requests.',
        answer='Maintain a bucket with capacity {burst}. Refill tokens as a function of elapsed monotonic time at {rate} tokens/s up to the capacity. Each admitted request consumes one token; when none are available, reject, queue within a bounded deadline, or return retry guidance according to API policy. Synchronize updates so concurrent callers cannot overspend the bucket. Use monotonic time so wall-clock adjustments do not create artificial refill. The burst capacity controls short spikes; the refill rate controls the long-run average.',
        verification='Must use monotonic elapsed-time refill, cap the bucket at {burst}, prevent concurrent overspend, and distinguish burst capacity from sustained rate {rate}/s.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service'], 'rate': [100, 500], 'burst': [20, 100]},
        tags=['rate-limit', 'token-bucket'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='bulk-write-chunking',
        topic='bulk-write-chunking',
        domain='software-engineering',
        subdomain='database',
        task_type='performance-analysis',
        question='A {service} writes {rows} rows one transaction at a time and spends most of its time in transaction/round-trip overhead. Analyze bounded bulk-write chunking.',
        answer='Measure per-transaction latency, server round trips, log/fsync behavior, lock duration, and throughput. Grouping rows into bounded transactions amortizes fixed commit and network cost, but extremely large transactions increase lock hold time, rollback work, replication lag, and memory pressure. Sweep chunk size and choose the knee that improves throughput while keeping latency and failure recovery acceptable. Preserve idempotency or retry semantics for a partially completed multi-chunk job.',
        verification='Must identify fixed transaction/round-trip overhead, explain why batching helps, include costs of oversized transactions, and require measured chunk-size selection.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service'], 'rows': [1000, 10000]},
        tags=['database', 'batching', 'throughput'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='memoization-concurrent-fill',
        topic='memoization-concurrent-fill',
        domain='software-engineering',
        subdomain='concurrency',
        task_type='code-repair',
        question='A thread-safe map is used for memoization in a {service}, but the code does `if key not in map: map[key] = compute()` and expensive computation still runs multiple times concurrently. Repair the pattern.',
        answer='A thread-safe container makes individual operations safe but does not make the compound check-then-compute sequence atomic. Use a per-key once/future/promise entry, a compute-if-absent primitive whose semantics guarantee the needed behavior, or a per-key lock. Avoid one global lock around all computations. Define failure behavior so a failed computation does not leave a permanently poisoned entry unless that is intentional.',
        verification='Must identify the compound-operation race, coalesce computation per key, avoid global serialization, and define cleanup after failed computation.',
        params={'service': ['API gateway', 'billing service', 'search service', 'media service', 'telemetry service']},
        tags=['memoization', 'race', 'singleflight'],
        levels=('advanced', 'expert'),
    ),
]
