from .base import F

FAMILIES = [
    F(
        id='otmpfile-publish',
        topic='otmpfile-publish',
        domain='systems-programming',
        subdomain='filesystems',
        task_type='implementation',
        question='A privileged tool must construct a new file privately and expose it by name only after all contents and metadata are valid. Design a Linux approach using an unnamed temporary inode when available.',
        answer='Create the file with `O_TMPFILE` in the target filesystem/directory, write and validate contents, set required metadata, and flush according to durability requirements. Only after the object is complete should it be linked into the namespace using the supported descriptor-relative mechanism. This avoids a partially initialized temporary pathname visible to other processes. Provide a safe fallback for filesystems without `O_TMPFILE`, and still handle directory durability when crash consistency matters.',
        verification='Must keep the object unnamed during construction, publish only after validation, stay on the target filesystem, and include a safe fallback/durability discussion.',
        params={'service': ['index builder', 'credential writer', 'package installer', 'state writer', 'cache builder']},
        tags=['o_tmpfile', 'atomic-publish'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='sendfile-partial',
        topic='sendfile-partial-transfer',
        domain='systems-programming',
        subdomain='io',
        task_type='code-repair',
        question='A server uses `sendfile()` once to transmit a {mb} MiB file and assumes the whole file was sent whenever the call returns a positive number. Repair the transfer loop.',
        answer='Treat the positive return as progress, not completion. Advance the offset and remaining byte count and continue until the requested range is fully sent. Handle `EINTR` by retrying, and handle `EAGAIN`/`EWOULDBLOCK` through the nonblocking readiness path. A zero return before the expected range completes needs policy appropriate to the file/source state. The loop must also respect platform limits on one-call transfer size.',
        verification='Must loop on partial positive results, preserve offset/progress, handle EINTR and nonblocking readiness, and not equate one successful call with full transfer.',
        params={'mb': [4, 64, 256, 1024, 2048]},
        tags=['sendfile', 'partial-io'],
        levels=('intermediate', 'advanced'),
    ),
    F(
        id='odirect-alignment',
        topic='odirect-alignment',
        domain='systems-programming',
        subdomain='storage',
        task_type='debugging',
        question='An application opens a file with `O_DIRECT` and gets `EINVAL` for some reads even though offsets and lengths look reasonable. Diagnose what must be checked on the target filesystem/device.',
        answer='Direct I/O commonly imposes alignment constraints on the user buffer, file offset, and I/O length, and the exact constraints are filesystem/device dependent. Inspect documented/statx-style alignment information where available and the actual buffer address, offset, and length. Allocate suitably aligned buffers and issue compatible sizes. Do not hard-code one universal 4096-byte rule: some stacks differ, and mixing buffered/direct I/O can add coherence complications.',
        verification='Must check buffer, offset, and length alignment against the actual filesystem/device requirements and reject a universal hard-coded alignment assumption.',
        params={'component': ['database', 'backup tool', 'log reader', 'benchmark', 'media pipeline']},
        tags=['o_direct', 'alignment'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='signal-safe-crash-path',
        topic='signal-safe-crash-path',
        domain='systems-programming',
        subdomain='signals',
        task_type='design',
        question='A process tries to call malloc, printf, and a complex logger from a fatal signal handler. It sometimes deadlocks while reporting a crash. Design a safer crash path.',
        answer='A signal can interrupt code while allocator/stdio/logger locks are held, so re-entering those subsystems from the handler can deadlock or corrupt state. Keep the handler minimal and limited to operations documented as async-signal-safe. Pre-open a descriptor or use a minimal fixed-format write if essential, record only basic signal/context information, then terminate or hand off to an external crash collector. Rich symbolization and heap inspection belong outside the unsafe signal context.',
        verification='Must explain reentrancy/lock hazards, restrict the handler to async-signal-safe operations, and move rich crash processing out of signal context.',
        params={'component': ['allocator', 'logger', 'runtime', 'server', 'agent']},
        tags=['signal', 'crash-handler', 'async-signal-safe'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='epoll-oneshot-rearm',
        topic='epoll-oneshot-rearm',
        domain='systems-programming',
        subdomain='event-loops',
        task_type='code-repair',
        question='A multi-threaded event loop uses `EPOLLONESHOT`. After one readiness event is handled, some sockets are never reported again. Repair the lifecycle.',
        answer='`EPOLLONESHOT` disables further notifications for that file descriptor after an event is delivered. After draining/processing the current readiness according to the nonblocking protocol, explicitly rearm the descriptor with `epoll_ctl(..., EPOLL_CTL_MOD, ...)`. Coordinate ownership so only the intended worker rearms it, and handle close/error races. If edge-triggered semantics are also used, drain until `EAGAIN` before rearming to avoid leaving unread work stranded.',
        verification='Must identify missing EPOLLONESHOT rearm, require explicit MOD rearm, and address nonblocking drain plus ownership/close races.',
        params={'component': ['proxy', 'chat server', 'storage daemon', 'broker', 'gateway']},
        tags=['epoll', 'oneshot', 'rearm'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='fcntl-lock-lifetime',
        topic='fcntl-lock-process-lifetime',
        domain='systems-programming',
        subdomain='file-locking',
        task_type='failure-analysis',
        question='A process uses traditional POSIX record locks and unexpectedly loses locks when an unrelated file descriptor for the same file is closed. Explain the trap.',
        answer="Traditional process-associated `fcntl` record-lock semantics can tie locks to the process/file relationship such that closing a descriptor for that file can affect the process's locks, even when another descriptor remains. This surprises code that treats descriptors as independent lock owners. Confirm the exact platform semantics and descriptor lifecycle. Where available, open-file-description locks or a dedicated locking discipline can give more predictable ownership. Do not assume all advisory lock APIs share identical lifetime rules.",
        verification='Must identify descriptor/lock lifetime semantics as the cause, require platform-specific confirmation, and avoid claiming every lock API behaves the same.',
        params={'component': ['database', 'indexer', 'daemon', 'package manager', 'scheduler']},
        tags=['fcntl', 'record-lock', 'lifetime'],
        levels=('advanced', 'expert'),
    ),
    F(
        id='splice-pipe-backpressure',
        topic='splice-pipe-backpressure',
        domain='systems-programming',
        subdomain='zero-copy',
        task_type='performance-analysis',
        question='A zero-copy pipeline uses `splice()` through a pipe between two file descriptors. Throughput stalls whenever the downstream side slows. Analyze the role of pipe capacity and backpressure.',
        answer='`splice()` can avoid copying through userspace, but data still flows through finite kernel pipe buffers. If the downstream destination cannot drain, the pipe fills and upstream splice calls block or return `EAGAIN` in nonblocking mode. Measure pipe/readiness behavior, downstream throughput, and syscall timing. Use bounded event-driven flow control and avoid assuming zero-copy means infinite buffering or no backpressure. Increasing pipe capacity may smooth bursts but does not fix a sustained downstream bottleneck.',
        verification='Must connect stalls to finite pipe capacity/downstream drain rate, preserve bounded backpressure, and reject the idea that zero-copy removes queueing limits.',
        params={'component': ['file relay', 'proxy', 'backup pipeline', 'media server', 'log shipper']},
        tags=['splice', 'pipe', 'backpressure'],
        levels=('advanced', 'expert'),
    ),
]
